services:
    underdevcrew.places_api.api_factory:
        class: Nekland\PlacesApi\Places
        # authentication is done in bundle extension class.


    underdevcrew.places_api.places:
        class: Nekland\PlacesApi\Api\Places
        factory: ["@underdevcrew.places_api.api_factory", getPlacesApi]
        calls:
            - ['setTransformer', ['@underdevcrew.places_api.places.model.transformer']]

    underdevcrew.places_api.places.model.transformer:
        class: UnderDevCrew\Bundle\PlacesApiBundle\Transformer\PlacesModelTransformer
        arguments: [ "@underdevcrew.places_api.places.model.factory" ]

    underdevcrew.places_api.places.model.factory:
        class: UnderDevCrew\Bundle\PlacesApiBundle\Factory\PlacesModelFactory
        arguments:
            - "@property_accessor"

    underdevcrew.places_api.search:
        class: Nekland\PlacesApi\Api\Search
        factory: ["@underdevcrew.places_api.api_factory", getSearchApi]
        calls:
            - ['setTransformer', ['@underdevcrew.places_api.search.model.transformer']]

    underdevcrew.places_api.search.model.transformer:
        class: UnderDevCrew\Bundle\PlacesApiBundle\Transformer\SearchModelTransformer
        arguments: [ "@underdevcrew.places_api.search.model.factory" ]

    underdevcrew.places_api.search.model.factory:
        class: UnderDevCrew\Bundle\PlacesApiBundle\Factory\SearchModelFactory
        arguments:
            - "@property_accessor"
            - "@underdevcrew.places_api.places.model.factory"


    underdevcrew.places_api.autocomplete:
        class: Nekland\PlacesApi\Api\Autocomplete
        factory: ["@underdevcrew.places_api.api_factory", getAutocompleteApi]
